import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
drv_cache.c
''')

if GetDepend(['BSP_USING_GPIO']):
    src += ['drv_gpio.c']

if GetDepend(['BSP_USING_UART']):
    src += ['drv_usart.c']

if GetDepend(['BSP_USING_SPI']):
    src += ['drv_spi.c']

if GetDepend(['BSP_USING_OSPI_FLASH']):
    src += ['drv_ospi_flash.c']

if GetDepend(['BSP_USING_LCD']):
    src += ['drv_lcd.c']

if GetDepend(['BSP_USING_USBD']):
    src += ['drv_usbd.c']

path = [cwd]


group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
